### ISSUE TITLE
Adding Widget is Unclear

### ISSUE THREAD

**Issue by ASUFLEXGITHUB** [dfyockey/RomanDigital#12]
When I wanted to add the widget, there was no clear way to add the widget in the widget setting page (see photo attached below). I later found out that I was to press the back button on the top left. That might not be clear for others. 
I was thinking a button on the bottom or top right of the widget settings saying 'Add Widget'. The new button could function as the back button on the top left.

![Screenshot_20241017_194144_RomanDigital.jpg](https://github.com/user-attachments/assets/8dd49377-4845-4360-9746-bd647e0ba077)

Otherwise, i like the idea of this app. This is a great start👍

**Comment by dfyockey** [comment]
That's a great idea! Thanks! Guess I was too close to it to see the lack of clarity.

I'll definitely add a button or the like in line with you're suggestion in the near future, as soon as the app's up on [F-Droid](https://f-droid.org). (It's in process now; wouldn't want to muck things up by making significant changes in the middle of their review.)

**Comment by dfyockey** [comment]
Further consideration of the issue revealed that an 'Add Widget' button wouldn't provide the best UX. That's because the same settings activity is used to reconfigure the widget at any time after it has been added, in which case such a button would likely confuse the user. Nevertheless, _something_ was needed to clarify the situation.

I decided to follow Samsung's model of providing 'Cancel' and 'Save' buttons to address the issue. To meet anticipated user expectations, I decided to provide these in both widget and app settings, and to provide undo of settings changes on cancellation.
